version: '3.3'
services:
  drupal:
    container_name: drupal-app
    image: drupal:8-apache
    ports: 
      - 80:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_sites:/var/www/html/sites
      - druapl_themes:/var/www/html/themes
    networks:
      - myappnet
    restart: always
    
  postgres:
    container_name: postgres_db
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ayaz123
    volumes:
     - psql_db_data:/var/lib/postgresql/data
    networks:
      - myappnet
    restart: always

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_sites:
  druapl_themes:
  psql_db_data:
networks:
  myappnet:
